version: '3.3'

services:
  test_db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=testpassword
    volumes:
      - my-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - test_db
volumes:
  my-db:
    driver: local
