# Use root/example as user/password credentials
version: '3.8'

services:
  api_service:
    container_name: api_service
    image: api_service
    build: ./
    ports:
      - 3000:3000
    command: npm start
    environment:
      DB_HOST: test_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: testpassword
      DB_NAME: mydb
    depends_on:
      test_db:
        condition: service_healthy

  test_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=testpassword
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - test_db
volumes:
  db:
    driver: local
